"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, CreditCard, LockKeyhole, MessageSquare, ShieldCheck, UserRound } from "lucide-react";
import type { OrderRecord, OrderStatusEvent } from "@/features/orders/types/orders";
import type { OrderBoosterAssignment, OrderWorkspaceMessage } from "@/features/orders/server/order-workspace-repository";
import { OrderStatusBadge } from "@/features/orders/components/order-status-badge";
import { OrderLiveChat } from "@/components/dashboard/order-live-chat";
import { OrderAccountDetails } from "@/components/dashboard/order-account-details";
import { OrderOperationsPanel } from "@/components/dashboard/order-operations-panel";
import { resolveRocketLeagueRank, RocketLeagueRankValue } from "@/components/orders/rocket-league-rank";
import { OrderConfigurationSummary } from "@/components/orders/order-configuration-summary";

interface Props { order:OrderRecord; history:OrderStatusEvent[]; checkoutState?:string; paymentError?:string; currentUserId:string; currentUserRole:"customer"|"booster"|"admin"; initialMessages:OrderWorkspaceMessage[]; boosterAssignment:OrderBoosterAssignment|null; mode?:"customer"|"booster"; boosterPayout?:number; backHref?:string; backLabel?:string; }
type Tab='overview'|'chat'|'evidence'|'details';
function money(v:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v)}
function date(v:string){return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v))}
function label(v:string){return v.replace(/([A-Z])/g,' $1').replace(/[_-]/g,' ').replace(/^./,l=>l.toUpperCase())}
function nextAction(order:OrderRecord, history:OrderStatusEvent[], boosterAssigned:boolean){const last=history.at(-1)?.toStatus;if(last==='in_progress'||order.status==='in_progress')return'Your booster is actively working on your service.';if((order.status==='paid'||order.status==='queued')&&boosterAssigned)return'Your booster has accepted the order and is preparing to start.';if(order.status==='paid'||order.status==='queued')return'Waiting for a booster to accept your order.';if(last==='completed'||order.status==='completed')return'This service has been completed.';if(order.status==='pending_payment')return'Complete payment to continue with this order.';return'Open the relevant tab for the latest order information.'}
function Progress({history,order,boosterAssigned}:{history:OrderStatusEvent[];order:OrderRecord;boosterAssigned:boolean}){const labels=['Payment','Assignment','In Progress','Completed'];const current=history.at(-1)?.toStatus;const reachedInProgress=history.some(event=>event.toStatus==='in_progress'||event.toStatus==='completed')||order.status==='in_progress'||order.status==='completed';const done=[order.paymentStatus==='paid',boosterAssigned,reachedInProgress,current==='completed'||order.status==='completed'];return <div className="flex min-w-0 items-center overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{labels.map((step,i)=><div key={step} className="flex items-center"><div className="flex items-center gap-2"><span className={`grid size-5 place-items-center rounded-full border ${done[i]?'border-[#39E56F]/20 bg-[#39E56F]/[0.05]':i===done.findIndex(x=>!x)?'border-cyan-300/25 bg-cyan-300/[0.06]':'border-white/[0.08]'}`}>{done[i]?<Check className="size-3 text-[#82F5A4]"/>:<span className="size-1.5 rounded-full bg-white/20"/>}</span><span className={`whitespace-nowrap text-[11px] ${done[i]?'text-[#AAB5AF]':'text-[#667069]'}`}>{step}</span></div>{i<3?<span className="mx-4 h-px w-8 bg-white/[0.07] sm:w-12"/>:null}</div>)}</div>}

export function CustomerOrderWorkspace({order,history,checkoutState,paymentError,currentUserId,currentUserRole,initialMessages,boosterAssignment,backHref='/dashboard/orders',backLabel='Orders'}:Props){
  const [tab,setTab]=useState<Tab>('overview'); const item=order.items[0]; const config=item?.configuration??{}; const currentValue=typeof config.currentRank!=='undefined'?config.currentRank:config.previousRank; const targetValue=config.targetRank; const currentRank=resolveRocketLeagueRank(currentValue); const targetRank=resolveRocketLeagueRank(targetValue); const suggestedPlatform=typeof config.platform==='string'?config.platform:undefined; const canPay=order.status==='pending_payment'&&order.paymentStatus!=='paid'; const isCustomerOwner=currentUserRole==='customer';
  const tabs:[Tab,string][]=[['overview','Overview'],['chat','Chat'],['evidence','Evidence'],['details','Details']];
  return <div className="mx-auto w-full max-w-[1540px] px-4 py-5 sm:px-6 lg:px-8">
    <div className="flex items-center justify-between gap-4 border-b border-white/[0.05] pb-3"><Link href={backHref} className="inline-flex items-center text-[12px] font-semibold text-[#A0AAA4] hover:text-white"><ArrowLeft className="mr-1.5 size-4"/>{backLabel}</Link><span className="font-gaming-value text-[11px] text-[#667069]">{order.orderNumber}</span></div>
    {checkoutState==='success'?<div className="mt-4 border-y border-[#39E56F]/15 py-3 text-[12px] text-[#82F5A4]">Payment submitted successfully. Stripe is confirming the payment.</div>:null}{checkoutState==='cancelled'?<div className="mt-4 border-y border-amber-300/15 py-3 text-[12px] text-amber-100">Checkout was cancelled. Your order is still saved.</div>:null}{paymentError?<div className="mt-4 border-y border-rose-300/15 py-3 text-[12px] text-rose-100">We could not start secure checkout. Please try again.</div>:null}
    <header className="grid gap-5 py-5 lg:grid-cols-[minmax(220px,.8fr)_minmax(360px,1.2fr)_auto] lg:items-center">
      <div className="min-w-0"><p className="font-gaming-label text-[10px] uppercase tracking-[0.14em] text-blue-200/50">{item?.gameName??'Gaming service'}</p><h1 className="mt-1 text-[26px] font-semibold tracking-[-0.04em] text-white">{item?.serviceName??'Order'}</h1><p className="mt-2 text-[11px] text-[#667069]">Created {date(order.createdAt)}</p></div>
      {(currentRank||targetRank)?<div className="flex min-w-0 items-center gap-5 lg:justify-center">{currentRank?<RocketLeagueRankValue value={currentValue} label="Current" size="lg"/>:null}{currentRank&&targetRank?<div className="flex min-w-12 flex-1 items-center sm:max-w-24"><span className="h-px flex-1 bg-blue-200/15"/><ArrowRight className="size-4 text-blue-200/35"/></div>:null}{targetRank?<RocketLeagueRankValue value={targetValue} label="Target" size="lg"/>:null}</div>:<div/>}
      <div className="flex items-center gap-4 lg:justify-end"><OrderStatusBadge status={order.status}/><div className="text-right"><p className="text-[11px] text-[#667069]">Order total</p><p className="font-gaming-value mt-0.5 text-[20px] font-bold text-white">{money(order.total)}</p></div></div>
    </header>
    <nav className="flex overflow-x-auto border-y border-white/[0.06] [scrollbar-width:none] [&::-webkit-scrollbar]:hidden" aria-label="Order workspace sections">{tabs.map(([key,text])=><button key={key} type="button" onClick={()=>setTab(key)} aria-current={tab===key?'page':undefined} className={`relative h-12 shrink-0 px-4 text-[12px] font-semibold transition-colors ${tab===key?'text-white':'text-[#75807A] hover:text-[#B6BFBA]'}`}>{text}{tab===key?<span className="absolute inset-x-3 bottom-0 h-0.5 bg-[#39E56F]"/>:null}</button>)}</nav>

    <div className="mt-6 grid gap-7 xl:grid-cols-[minmax(0,1fr)_350px] 2xl:grid-cols-[minmax(0,1fr)_380px]">
      <main className="min-w-0">
        {tab==='overview'?<div className="space-y-7"><section><p className="font-gaming-label text-[10px] uppercase tracking-[0.13em] text-[#667069]">Current Status</p><h2 className="mt-1 text-[19px] font-semibold text-white">{history.at(-1)?.toStatus?label(history.at(-1)!.toStatus):label(order.status)}</h2><p className="mt-2 text-[13px] leading-6 text-[#A0AAA4]">{nextAction(order,history,Boolean(boosterAssignment))}</p></section><section className="border-t border-white/[0.05] pt-5"><h2 className="text-[17px] font-semibold text-white">Progress</h2><div className="mt-4"><Progress history={history} order={order} boosterAssigned={Boolean(boosterAssignment)}/></div></section>{boosterAssignment?<section className="border-t border-white/[0.05] pt-5"><h2 className="text-[17px] font-semibold text-white">Booster Summary</h2><div className="mt-3 flex items-center gap-3"><span className="grid size-11 place-items-center overflow-hidden rounded-full border border-white/[0.08] bg-[#0E1411] text-[12px] font-bold">{boosterAssignment.avatarUrl?<img src={boosterAssignment.avatarUrl} alt="" className="h-full w-full object-cover"/>:boosterAssignment.displayName[0]?.toUpperCase()}</span><div><p className="text-[13px] font-semibold text-white">{boosterAssignment.displayName}</p><p className="mt-0.5 text-[11px] text-[#667069]">Assigned Booster</p></div><button type="button" onClick={()=>setTab('chat')} className="ml-auto text-[11px] font-semibold text-[#82F5A4]">Message booster</button></div></section>:null}</div>:null}
        {tab==='chat'?<section className="min-h-[calc(100dvh-290px)]"><OrderLiveChat orderId={order.id} currentUserId={currentUserId} initialMessages={initialMessages}/></section>:null}
        {tab==='evidence'?<section><div className="mb-4"><h2 className="text-[19px] font-semibold text-white">Order Evidence</h2><p className="mt-1 text-[12px] text-[#667069]">Starting and completion proof attached to this order.</p></div><OrderOperationsPanel orderId={order.id} canManage={false} suggestedPlatform={suggestedPlatform} orderStatus={order.status}/></section>:null}
        {tab==='details'?<div className="space-y-7">{item?<section><h2 className="text-[19px] font-semibold text-white">Service Configuration</h2><div className="mt-3"><OrderConfigurationSummary configuration={item.configuration} priceBreakdown={item.priceBreakdown}/></div></section>:null}<section className="border-t border-white/[0.05] pt-5"><h2 className="text-[19px] font-semibold text-white">Pricing</h2><div className="mt-3 divide-y divide-white/[0.05] border-y border-white/[0.05]">{item?.priceBreakdown.map((line,index)=><div key={`${line.label}-${index}`} className="flex items-center justify-between gap-4 py-3"><span className="text-[12px] text-[#A0AAA4]">{line.label}</span><span className={`font-gaming-value text-[12px] font-bold ${line.amount<0?'text-[#82F5A4]':'text-white'}`}>{line.amount<0?'−':''}{money(Math.abs(line.amount))}</span></div>)}<div className="flex items-end justify-between gap-4 py-4"><span className="text-[12px] font-semibold text-white">Total</span><span className="font-gaming-value text-[20px] font-bold text-white">{money(order.total)}</span></div></div></section></div>:null}
      </main>

      <aside className="min-w-0 xl:sticky xl:top-[76px] xl:self-start"><div className="border-y border-white/[0.06]">
        <section className="py-4"><div className="flex items-center gap-2"><UserRound className="size-4 text-[#667069]"/><h2 className="text-[14px] font-semibold text-white">Assigned Booster</h2></div>{boosterAssignment?<div className="mt-3 flex items-center gap-3"><span className="grid size-12 place-items-center overflow-hidden rounded-full border border-white/[0.08] bg-[#0E1411] text-[12px] font-bold">{boosterAssignment.avatarUrl?<img src={boosterAssignment.avatarUrl} alt="" className="h-full w-full object-cover" referrerPolicy="no-referrer"/>:boosterAssignment.displayName[0]?.toUpperCase()}</span><div className="min-w-0"><p className="truncate text-[13px] font-semibold text-white">{boosterAssignment.displayName}</p><p className="mt-0.5 text-[11px] text-[#667069]">Assigned Booster</p></div><button type="button" onClick={()=>setTab('chat')} className="ml-auto text-[11px] font-semibold text-[#82F5A4]">Message</button></div>:<p className="mt-3 text-[12px] leading-5 text-[#A0AAA4]">Your booster will appear here once the order is accepted.</p>}</section>
        <section className="border-t border-white/[0.05] py-4"><div className="flex items-center gap-2"><CreditCard className="size-4 text-[#667069]"/><h2 className="text-[14px] font-semibold text-white">Payment</h2></div><div className="mt-3 flex items-end justify-between"><div><p className="text-[11px] text-[#667069]">Order total</p><p className="font-gaming-value mt-0.5 text-[20px] font-bold text-white">{money(order.total)}</p><p className="mt-1 text-[11px] text-[#667069]">{order.paymentStatus==='paid'?'Stripe confirmed':order.paymentStatus==='pending'?'Payment pending':'Payment not completed'}</p></div><span className={`text-[11px] font-semibold ${order.paymentStatus==='paid'?'text-[#82F5A4]':'text-[#A0AAA4]'}`}>{label(order.paymentStatus)}</span></div>{canPay?<form action="/api/checkout" method="post" className="mt-4"><input type="hidden" name="orderId" value={order.id}/><button className="h-10 w-full rounded-lg bg-[#39E56F] text-[11px] font-semibold text-[#050807] hover:bg-[#55ED82]">Complete secure payment</button></form>:null}</section>
        <section className="border-t border-white/[0.05] py-4"><div className="flex items-center gap-2"><LockKeyhole className="size-4 text-[#667069]"/><h2 className="text-[14px] font-semibold text-white">Secure Account Access</h2></div>{boosterAssignment?<div className="mt-3"><OrderAccountDetails orderId={order.id} canEdit={isCustomerOwner}/></div>:<p className="mt-3 text-[12px] text-[#667069]">Available after booster assignment.</p>}</section>
        <section className="border-t border-white/[0.05] py-4"><div className="flex items-start gap-2.5"><ShieldCheck className="mt-0.5 size-4 text-[#667069]"/><div><p className="text-[12px] font-semibold text-[#AAB5AF]">Protected by BoostingPedia</p><p className="mt-1 text-[11px] leading-5 text-[#667069]">Keep communication and payments on-platform.</p></div></div></section>
      </div></aside>
    </div>
  </div>
}
