create table if not exists public.legal_consents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  terms_version text not null,
  privacy_version text not null,
  cookie_version text not null,
  refund_version text not null,
  age_or_guardian_confirmed boolean not null default false,
  accepted_at timestamptz not null,
  source text not null default 'registration',
  created_at timestamptz not null default now()
);

create index if not exists legal_consents_user_id_idx
  on public.legal_consents(user_id);

alter table public.legal_consents enable row level security;

drop policy if exists "Users can read their own legal consent" on public.legal_consents;
create policy "Users can read their own legal consent"
on public.legal_consents
for select
to authenticated
using (auth.uid() = user_id);

grant select on table public.legal_consents to authenticated;

create or replace function public.record_signup_legal_consent()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  consent_version text;
  consent_accepted_at timestamptz;
begin
  if coalesce((new.raw_user_meta_data ->> 'legal_consent')::boolean, false) is not true then
    return new;
  end if;

  consent_version := coalesce(
    new.raw_user_meta_data ->> 'legal_consent_version',
    '2026-08-30'
  );

  consent_accepted_at := coalesce(
    (new.raw_user_meta_data ->> 'legal_consent_accepted_at')::timestamptz,
    now()
  );

  insert into public.legal_consents (
    user_id,
    terms_version,
    privacy_version,
    cookie_version,
    refund_version,
    age_or_guardian_confirmed,
    accepted_at,
    source
  )
  values (
    new.id,
    consent_version,
    consent_version,
    consent_version,
    consent_version,
    coalesce(
      (new.raw_user_meta_data ->> 'age_or_guardian_confirmed')::boolean,
      false
    ),
    consent_accepted_at,
    'registration'
  );

  return new;
end;
$$;

drop trigger if exists on_auth_user_record_legal_consent on auth.users;

create trigger on_auth_user_record_legal_consent
after insert on auth.users
for each row
execute function public.record_signup_legal_consent();
